### PR TITLE
Fixes namespace issue when formatting in xml

### PR DESCRIPTION
**Pull request by blundell**
Before | After 
-------|-------
screen shot 2015-06-20 at 23 00 54|screen shot 2015-06-20 at 23 01 01
second fragment xmlns is in the wrong place|now its in the right place (at the top)

The fix was because the namespace we use was not being recognised by the formatting, hence it was never satisfying rule number **(1)** always rule **(5)**. Fixed this by changing the reg to match any namespace for rule (1).

Before|After
-----|-----
screen shot 2015-06-20 at 22 56 54|screen shot 2015-06-20 at 22 55 39

The things exported into the jar are the normal:

screen shot 2015-06-20 at 22 58 23

### CODE REVIEW

**Comment by ataulm** [comment]
:+1: 

what if you have multiple NS declarations, e.g. android and res-auto?

**Comment by blundell** [comment]
it works as expected

**Comment by blundell** [comment]
this also fixes the annoying change to AndroidManifest whenever we touched it :+1:

**Comment by ataulm** [comment]
That's the only time I experienced the bug - I never put xmlns in non-root
elements :D

On Sat, 20 Jun 2015 at 23:47 Paul Blundell <notifications@github.com> wrote:

> this also fixes the annoying change to AndroidManifest whenever we touched
> it [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/novoda/novoda/pull/9#issuecomment-113834725>.
>

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by blundell** [comment]
no neither do i as a rule, the SS's are a made up case. :+1:

**Comment by rock3r** [comment]
My question is: why do you even have xmlns declarations in non-root elements? That said, :100:

**Comment by xrigau** [comment]
this broke my settings because it set the line delimiter to 120 instead of 150 :-1: bad man @blundell

**Comment by blundell** [comment]
:scream: what!

**Comment by xrigau** [comment]
forgot to say nice fix anyway :+1: @blundell

**Pull request merged**
