### PR TITLE
Allows more readability of RX code

### PR DESCRIPTION
**Pull request by blundell**
- enforced brackets for if statements

The small change for Rx is to say, newline after a ( when using method call args
screen shot 2015-03-29 at 11 30 43

I believe this makes the methods line up more naturally and it is easier to see now which overrides are for which method call.

Before:
```java
final Observable<Cursor> cursorObservable = Observable.create(new Observable.OnSubscribe<Cursor>() {
            @Override
            public void call(Subscriber<? super Cursor> subscriber) {
                   // java
            }
        });

        cursorObservable.onErrorResumeNext(new Func1<Throwable, Observable<? extends Cursor>>() {
            @Override
            public Observable<? extends Cursor> call(Throwable throwable) {
                // java
                return Observable.error(throwable);
            }
        })
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<Cursor>() {
            @Override
            public void onCompleted() {
                // no-op
            }

            @Override
            public void onError(Throwable e) {
                Log.e(e, "Something broke but we don't handle it yet");
            }

            @Override
            public void onNext(Cursor result) {
                // java
            }
        });
```
After:
```java
final Observable<Cursor> cursorObservable = Observable.create(
                new Observable.OnSubscribe<Cursor>() {
                    @Override
                    public void call(Subscriber<? super Cursor> subscriber) {
                        // java
                    }
                });

        cursorObservable.onErrorResumeNext(
                new Func1<Throwable, Observable<? extends Cursor>>() {
                    @Override
                    public Observable<? extends Cursor> call(Throwable throwable) {
                        // java
                        return Observable.error(throwable);
                    }
                })
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(
                        new Observer<Cursor>() {
                            @Override
                            public void onCompleted() {
                                // no-op
                            }

                            @Override
                            public void onError(Throwable e) {
                                Log.e(e, "Something broke but we don't handle it yet");
                            }

                            @Override
                            public void onNext(Cursor result) {
                                // java
                            }
                        });
```
As a diff: https://www.diffchecker.com/6a0ddusm

I exported everything except those that are local or UI or keyboard chars - i feel everyone at Novoda should start on the same guidelines:
screen shot 2015-03-30 at 11 13 00

Enforcing brackets means when you format your if statements will be given brackets:
screen shot 2015-03-29 at 11 31 27
screen shot 2015-03-29 at 11 31 21
screen shot 2015-03-29 at 11 31 13
screen shot 2015-03-29 at 11 30 52

Also created a template for equals and hashcode for Novoda, I assume this will be in the jar but not 100% - either way at the moment it is just a copy of the intellij one and next step is to change it to force brackets inclusion and simplify!

screen shot 2015-03-29 at 11 45 45

### CODE REVIEW

**Comment by stefanhoth** [comment]
Rx code in general looks hardly readable but this is an improvement. :+1:

**Comment by ataulm** [comment]
does it only force the newline if there are more than one param?

**Comment by ataulm** [comment]
i.e. why didn't it do:

```java
Log.e(
    e,
    "Something broke but we don't handle it yet"
);
```

**Comment by devisnik** [comment]
Reads much better.
Would be even nicer if the closing `);` would align with the call to `subscribe()`.

In general I think an inner class is easiest to read when it aligns with the method that uses it.

**Comment by blundell** [comment]
@ataulm not sure, maybe because those params are references - the rule I've added combines with other rules.

This new jar needs a Novoda volunteer to take the leap of faith :-)

**Comment by rock3r** [comment]
@blundell you should _not_ export UI settings (IDE theme, color schemes, editor font etc). That'll likely cause issues and/or annoy people.

**Comment by rock3r** [comment]
(I know you didn't export the L&F, by the way, it was a broader statement)

**Comment by blundell** [comment]
sorry which ones? I thought all UI was `Look & Feel`.

What is SDK table? I was thinking prefer all being consistent

**Comment by ouchadam** [comment]
yeah with what @rock3r said, there's a lot of settings you'll overwrite, should only export the modification, git and github for example will probably break

**Comment by blundell** [comment]
"will probably break" , explain more

**Comment by ouchadam** [comment]
git takes a git binary location, for example for me it's `/usr/bin/git` and I don't use `github` so all my fields are empty in there

**Comment by ouchadam** [comment]
basically any path within the settings will be overwritten with yours!

**Comment by blundell** [comment]
kk let me thin this down

**Comment by rock3r** [comment]
Yeah, GitHub settings are mostly username/pass/auth token, for example:

screenshot 2015-03-30 11 09 33

SDK table is a legacy IDEA thing which is "hidden" in AS but basically include paths to JDK and Android SDK, plus all the various configured SDKs (again JDKs and Android SDK and whatevers). In IDEA it looks like this:

screenshot 2015-03-30 11 12 25

And so on. basically you can see what each setting you're exporting is (SDK table aside) by just looking it up in the preferences.

**Comment by blundell** [comment]
removed SDK tables and other UI elements

**Comment by rock3r** [comment]
What did you export this time @blundell? So me and @ouchadam can double-check

**Comment by blundell** [comment]
see desc ^

**Comment by ataulm** [comment]
"menus/toolbars customisations" -> my AS is extremely thinned down for menus.

**Comment by rock3r** [comment]
@blundell if it's like desc minus SDK tables and "UI elements" (which ones?) then it's still :x: for me (see git/github/menus/etc)

**Comment by blundell** [comment]
`menus/toolbars customisations` @ataulm we should export these for new starters they need the menu setup the same as everyone, but yes when you "import" these settings you can untick this selection box.
(You can also make a PR to improve our default menu's!)

**Comment by blundell** [comment]
@rock3r I think you need to press refresh

**Comment by rock3r** [comment]
@blundell true dat (was cached probably, had to force-refresh). Probably PSI settings could be skipped as well, but whatever. Looks better now :+1:

**Comment by blundell** [comment]
any chance ppl?

**Comment by ouchadam** [comment]
@ataulm tried it and it broke all his stuff

**Comment by stefanhoth** [comment]
@blundell Care to try again, i.e. start from the current version and reenter your changes with a minimal scope?

**Comment by blundell** [comment]
@ataulm what broke? The problem/solution is for current employee's they need to selectively apply the brackets update. Whereas this settings.jar is for new starters who have a blank slate.  Maybe we should pair walk though if you think there are issues.

i.e. current employee's take this at the beginning and then can add their own customisations on top (code folding, menus etc) but we need a solid base for new starters.

**Comment by ataulm** [comment]
For me, the thing that broke was XML ordering of attributes (e.g. puts package before namespace in Manifest):

- this only occurs if you have "rearrange entries" switched on when you do "format code"
- this formatting rule is already in the current version in master

so this change doesn't _introduce_ anything lame, and does introduce something good and agreed on, :+1: from me

**Comment by Dorvaryn** [comment]
Looks good. Thanks for the effort !

**Comment by xrigau** [comment]
the damage is done

**Pull request merged**
