### PR TITLE
Adds new equals template

### PR DESCRIPTION
**Pull request by blundell**
This template will prefer the positive (return true not false when comparing) and simplify if statements with concatenation (&&)

| Array in last position | 
| ---- |
| array in last position 

All non null | 
| ----- |
| all non null 

All nullable |
| ----- |
| all nullable

The old template took up a lot more space and had that really annoying yellow IDE warning recommending it can be simplified, now the robots simplify it always!

| old |
| ----- |
| old2

You use this new template by selecting it from the drop down

how to

### CODE REVIEW

**Comment by Electryc** [comment]
I like! :+1:

**Comment by ouchadam** [comment]
:100:

**Comment by stefanhoth** [comment]
:100: for better readability :exclamation: 

That light theme though... :eyes::fire:

**Comment by juankysoriano** [comment]
Much better, thanks @blundell

**Comment by Hutch4** [comment]
:+1:

**Comment by hhaouat** [comment]
Thanks @blundell :+1:

**Comment by alexstyl** [comment]
LGTM, but
if we don't like `Arrays.equals`, why don't we replace it with something else?

**Comment by blundell** [comment]
@alexstyl this is true, the "contract" for the equals is based on IntelliJ's equals and this adds the comments about arrays. So yes if we want :) but not this PR

**Comment by mr-archano** [comment]
LGTM :+1:

**Comment by blundell** [comment]
shipped! https://github.com/novoda/novoda/commit/dd66c9cde5e10657b17c09cd662d75431aa20bf8

**Pull request merged**
