### PR TITLE
PT-408: Publish static analysis rules artifact

### PR DESCRIPTION
**Pull request by tobiasheine**
Tracked by [PT-408](https://novoda.atlassian.net/browse/PT-408)

## This PR adds

We want to archive and versionize our static analysis rules in a jar, release it to bintray and bundle them together with the static analysis plugin using the [maven artifact feature](https://github.com/novoda/gradle-static-analysis-plugin/pull/27). This will be useful for new projects and for people that are happy with a base set of rules and don't want to dig into customising them.

This PR turns the repo into a gradle project and configures the upload to bintray. This is the [CI job](https://ci.novoda.com/view/Open%20source/job/static-analysis-rules/) which does the release.

## Considerations and implementation

- fixed outdated `README` since the plugin now supports android lint and detekt
- migrate the repo into a gradle project
- added an additional subfolder to separate the `team-props` from the gradle project
- configure the bintray upload in the `publish-rules.gradle`

### CODE REVIEW

**Comment by tobiasheine** [comment]
Putting ❌ until the CI job is configured

**Comment by rock3r** [comment]
@tobiasheine, what about the point that was raised yesterday about the inextensibility/inflexibility? Is it written down somewhere? I'd like to know what happened since it was discussed, and what's the rationale behind this going ahead since there were several doubts (mostly on my side, sure).

**Comment by tobiasheine** [comment]
@rock3r, we agreed on that using a rule artefact as base for novoda projects is currently not feasible due to the limitation that we can't overwrite single rules locally.  
But we also came to the conclusion that we want to provide a very easy way for people to get started with the static analysis tools and our plugin. For these people we can minimise the configuration effort  plus we provide a convenient way to keep their ruleset up to date.

**Comment by mr-archano** [comment]
@rock3r remember also that using the artifact is not a full opt-in, as you have to define manually which file to use from the jar. In the end this is the only thing that this approach really provides: a versioned container for configuration files.

**Comment by lgvalle** [comment]
This will publish the content of `./team-props/static-analysis` as a `jar` artifact with the name `static-analysis-rules` right?
Then any user of the plugin can download and use this rules with:
```
staticAnalysis {
  rules {
    novoda {
      maven 'com.novoda:static-analysis-rules:0.1'
    }
  }
  checkstyle {
    config rules.novoda['checkstyle/modules.xml']
  }
}
```

They can also decide to ignore this and provide their own rule files. 
Or they can release their own artifact containing a set of rules that work better for themselves. Shall we include a paragraph explaining how's the content of the jar file expected to be for this case?

**Pull request merged**
