### PR TITLE
Increase line limit from 100 to 150 columns.

### PR DESCRIPTION
**Pull request by HenriqueRocha**
Because the line limit was set to 100 I got another PR not accepted because I was breaking lines to early.
This might help newbies some frustration on getting PRs merged.

### CODE REVIEW

**Comment by zegnus** [comment]
For newbies as well, you can go through our Hackpad articles:

 - Best Practices & Tips: https://novoda.hackpad.com/ep/group/mTmVOSEnYKe
 - Style & Code Conventions: https://novoda.hackpad.com/Style-Code-Conventions-GBMbnn7aSoB

In the latter you will find the line length ;)

**Comment by blundell** [comment]
it's strange that it was set to 100 :/ I'm thinking our settings has been screwed up at some point!

**Comment by blundell** [comment]
Problem is everytime we just have to accept the jar file. Maybe we need screenies to prove change :)

**Comment by blundell** [comment]
@HenriqueRocha is this PR now superceeded by #6 ?

**Comment by blundell** [comment]
re-open if it is not

**Comment by HenriqueRocha** [comment]
Yes, you can ignore this PR.

**Pull request closed without merging**
