### PR TITLE
Remove custom eq hash

### PR DESCRIPTION
**Pull request by ataulm**
There is a bug in the equals template which manifests if classes allow null fields. As it's generated code anyway, not much reason to customise it

- Delete the file: `<AS/Intellij settings dir>/config/options/equalsHashCodeTemplates.xml`
- Import the new `novoda-settings.jar`

On Mac/Linux, the settings directory should be in your home directory - mine was `~/.AndroidStudio2.1`.

delete_me

You must manually delete the file, then import the new `novoda-settings.jar` (or the other way around). Even though the customisation has been removed from the jar, Android Studio will not delete it locally and so it will be available when you generate.

### CODE REVIEW

**Comment by joetimmins** [comment]
Nice work! LGTM 👍

**Comment by blundell** [comment]
👎 so nobody could work out what the fix was

**Comment by tasomaniac** [comment]
I know this class is recently changed by @blundell in #17 
I didn't understand why we deleted completely? And also not everybody is following here. I think this should be clearly communicated in the slack. I couldn't find the discussion.

**Comment by rock3r** [comment]
Said this was discussed on #g-developers

**Comment by tasomaniac** [comment]
Oh I see, it was discussed in the morning. I missed it. Sorry.

**Pull request merged**
